// Currency display names from Unicode CLDR, retrieved 2026-09-26.
// Sources: https://github.com/unicode-org/cldr-json/tree/main/cldr-json/cldr-numbers-full/main
// ar/currencies.json and bn/currencies.json. ISO codes remain unchanged.
import 'package:flutter/foundation.dart';

const String shopCurrencyDataLicense = '''
UNICODE LICENSE V3

COPYRIGHT AND PERMISSION NOTICE

Copyright © 2015-2024 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.

IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.

SPDX-License-Identifier: Unicode-3.0
''';

bool _currencyLicenseRegistered = false;

/// Registers the shipped CLDR data notice in Flutter's license page.
void registerShopTrackLocalizationLicenses() {
  if (_currencyLicenseRegistered) return;
  _currencyLicenseRegistered = true;
  LicenseRegistry.addLicense(() async* {
    yield LicenseEntryWithLineBreaks(const [
      'Unicode CLDR currency names',
    ], shopCurrencyDataLicense);
  });
}

const Map<String, String> shopArabicCurrencyNames = {
  'Afghani': 'أفغاني',
  'Lek': 'ليك ألباني',
  'Armenian Dram': 'درام أرميني',
  'Kwanza': 'كوانزا أنغولي',
  'Argentine Peso': 'بيزو أرجنتيني',
  'Australian Dollar': 'دولار أسترالي',
  'Aruban Florin': 'فلورن أروبي',
  'Azerbaijan Manat': 'مانات أذربيجان',
  'Convertible Mark': 'مارك البوسنة والهرسك قابل للتحويل',
  'Barbados Dollar': 'دولار بربادوسي',
  'Bahraini Dinar': 'دينار بحريني',
  'Burundi Franc': 'فرنك بروندي',
  'Bermudian Dollar': 'دولار برمودي',
  'Brunei Dollar': 'دولار بروناي',
  'Boliviano': 'بوليفيانو بوليفي',
  'Brazilian Real': 'ريال برازيلي',
  'Bahamian Dollar': 'دولار باهامي',
  'Ngultrum': 'نولتوم بوتاني',
  'Pula': 'بولا بتسواني',
  'Belarusian Ruble': 'روبل بيلاروسي',
  'Belize Dollar': 'دولار بليزي',
  'Canadian Dollar': 'دولار كندي',
  'Congolese Franc': 'فرنك كونغولي',
  'Swiss Franc': 'فرنك سويسري',
  'Chilean Peso': 'بيزو تشيلي',
  'Colombian Peso': 'بيزو كولومبي',
  'Costa Rican Colon': 'كولن كوستاريكي',
  'Cuban Peso': 'بيزو كوبي',
  'Cabo Verde Escudo': 'اسكودو الرأس الأخضر',
  'Czech Koruna': 'كرونة تشيكية',
  'Djiboutian Franc': 'فرنك جيبوتي',
  'Danish Krone': 'كرونة دنماركية',
  'Dominican Peso': 'بيزو الدومنيكان',
  'Algerian Dinar': 'دينار جزائري',
  'Egyptian Pound': 'جنيه مصري',
  'Nakfa': 'ناكفا أريتري',
  'Ethiopian Birr': 'بير أثيوبي',
  'Fiji Dollar': 'دولار فيجي',
  'Falkland Islands Pound': 'جنيه جزر فوكلاند',
  'Lari': 'لارى جورجي',
  'Ghana Cedi': 'سيدي غانا',
  'Gibraltar Pound': 'جنيه جبل طارق',
  'Dalasi': 'دلاسي غامبي',
  'Guinean Franc': 'فرنك غينيا',
  'Quetzal': 'كوتزال غواتيمالا',
  'Guyana Dollar': 'دولار غيانا',
  'Hong Kong Dollar': 'دولار هونغ كونغ',
  'Lempira': 'ليمبيرا هنداروس',
  'Gourde': 'جوردى هايتي',
  'Forint': 'فورينت هنغاري',
  'Rupiah': 'روبية إندونيسية',
  'New Israeli Sheqel': 'شيكل إسرائيلي جديد',
  'Iraqi Dinar': 'دينار عراقي',
  'Iranian Rial': 'ريال إيراني',
  'Iceland Krona': 'كرونة أيسلندية',
  'Jamaican Dollar': 'دولار جامايكي',
  'Jordanian Dinar': 'دينار أردني',
  'Kenyan Shilling': 'شلن كينيي',
  'Som': 'سوم قيرغستاني',
  'Riel': 'رييال كمبودي',
  'Comorian Franc': 'فرنك جزر القمر',
  'North Korean Won': 'وون كوريا الشمالية',
  'Won': 'وون كوريا الجنوبية',
  'Kuwaiti Dinar': 'دينار كويتي',
  'Cayman Islands Dollar': 'دولار جزر كيمن',
  'Tenge': 'تينغ كازاخستاني',
  'Lao Kip': 'كيب لاوسي',
  'Lebanese Pound': 'جنيه لبناني',
  'Sri Lanka Rupee': 'روبية سريلانكية',
  'Liberian Dollar': 'دولار ليبيري',
  'Loti': 'لوتي ليسوتو',
  'Libyan Dinar': 'دينار ليبي',
  'Moroccan Dirham': 'درهم مغربي',
  'Moldovan Leu': 'ليو مولدوفي',
  'Malagasy Ariary': 'أرياري مدغشقر',
  'Denar': 'دينار مقدوني',
  'Kyat': 'كيات ميانمار',
  'Tugrik': 'توغروغ منغولي',
  'Pataca': 'باتاكا ماكاوي',
  'Ouguiya': 'أوقية موريتانية',
  'Mauritius Rupee': 'روبية موريشيوسية',
  'Rufiyaa': 'روفيه جزر المالديف',
  'Malawi Kwacha': 'كواشا مالاوي',
  'Mexican Peso': 'بيزو مكسيكي',
  'Malaysian Ringgit': 'رينغيت ماليزي',
  'Mozambique Metical': 'متكال موزمبيقي',
  'Namibia Dollar': 'دولار ناميبي',
  'Naira': 'نايرا نيجيري',
  'Cordoba Oro': 'قرطبة نيكاراغوا',
  'Norwegian Krone': 'كرونة نرويجية',
  'Nepalese Rupee': 'روبية نيبالي',
  'New Zealand Dollar': 'دولار نيوزيلندي',
  'Rial Omani': 'ريال عماني',
  'Balboa': 'بالبوا بنمي',
  'Sol': 'سول بيروفي',
  'Kina': 'كينا بابوا غينيا الجديدة',
  'Philippine Peso': 'بيزو فلبيني',
  'Pakistan Rupee': 'روبية باكستاني',
  'Zloty': 'زلوتي بولندي',
  'Guarani': 'غواراني باراغواي',
  'Qatari Rial': 'ريال قطري',
  'Romanian Leu': 'ليو روماني',
  'Serbian Dinar': 'دينار صربي',
  'Russian Ruble': 'روبل روسي',
  'Rwanda Franc': 'فرنك رواندي',
  'Solomon Islands Dollar': 'دولار جزر سليمان',
  'Seychelles Rupee': 'روبية سيشيلية',
  'Sudanese Pound': 'جنيه سوداني',
  'Swedish Krona': 'كرونة سويدية',
  'Singapore Dollar': 'دولار سنغافوري',
  'Saint Helena Pound': 'جنيه سانت هيلين',
  'Leone': 'ليون سيراليوني',
  'Somali Shilling': 'شلن صومالي',
  'Surinam Dollar': 'دولار سورينامي',
  'South Sudanese Pound': 'جنيه جنوب السودان',
  'Dobra': 'دوبرا ساو تومي وبرينسيبي',
  'El Salvador Colon': 'كولون سلفادوري',
  'Syrian Pound': 'ليرة سورية',
  'Lilangeni': 'ليلانجيني سوازيلندي',
  'Baht': 'باخت تايلاندي',
  'Somoni': 'سوموني طاجيكستاني',
  'Turkmenistan New Manat': 'مانات تركمانستان',
  'Tunisian Dinar': 'دينار تونسي',
  'Pa’anga': 'بانغا تونغا',
  'Turkish Lira': 'ليرة تركية',
  'Trinidad and Tobago Dollar': 'دولار ترينداد وتوباغو',
  'New Taiwan Dollar': 'دولار تايواني',
  'Tanzanian Shilling': 'شلن تنزاني',
  'Hryvnia': 'هريفنيا أوكراني',
  'Uganda Shilling': 'شلن أوغندي',
  'Peso Uruguayo': 'بيزو اوروغواي',
  'Uzbekistan Sum': 'سوم أوزبكستاني',
  'Bolívar Soberano': 'بوليفار فنزويلي',
  'Dong': 'دونج فيتنامي',
  'Vatu': 'فاتو فانواتو',
  'Tala': 'تالا ساموا',
  'Central African CFA Franc': 'فرنك وسط أفريقي',
  'East Caribbean Dollar': 'دولار شرق الكاريبي',
  'Caribbean Guilder': 'غيلدر كاريبي',
  'CFA Franc BCEAO': 'فرنك غرب أفريقي',
  'CFP Franc': 'فرنك سي إف بي',
  'Yemeni Rial': 'ريال يمني',
  'Rand': 'راند جنوب أفريقيا',
  'Zambian Kwacha': 'كواشا زامبي',
  'Zimbabwe Gold': 'ذهب زيمبابوي',
};

const Map<String, String> shopBanglaCurrencyNames = {
  'Afghani': 'আফগান আফগানি',
  'Lek': 'আলবেনিয়ান লেক',
  'Armenian Dram': 'আরমেনিয়ান দ্রাম',
  'Kwanza': 'এ্যাঙ্গোলান কওয়ানজা',
  'Argentine Peso': 'আর্জেন্টিনা পেসো',
  'Australian Dollar': 'অস্ট্রেলিয়ান ডলার',
  'Aruban Florin': 'আরুবা ফ্লোরিন',
  'Azerbaijan Manat': 'আজারবাইজান মানাত',
  'Convertible Mark': 'বসনিয়া এবং হার্জেগোভিনা বিনিমেয় মার্ক',
  'Barbados Dollar': 'বার্বেডোজ ডলার',
  'Bahraini Dinar': 'বাহরাইনি দিনার',
  'Burundi Franc': 'বুরুন্ডি ফ্রাঙ্ক',
  'Bermudian Dollar': 'বারমিউডান ডলার',
  'Brunei Dollar': 'ব্রুনেই ডলার',
  'Boliviano': 'বলিভিয়ান বলিভিয়ানো',
  'Brazilian Real': 'ব্রাজিলিয়ান রিয়েল',
  'Bahamian Dollar': 'বাহামিয়ান ডলার',
  'Ngultrum': 'ভুটানি এনগুল্ট্রুম',
  'Pula': 'বতসোয়ানা পুলা',
  'Belarusian Ruble': 'বেলারুশিয়ান রুবেল',
  'Belize Dollar': 'বেলিজ ডলার',
  'Canadian Dollar': 'কানাডিয়ান ডলার',
  'Congolese Franc': 'কঙ্গোলিস ফ্র্যাঙ্ক',
  'Swiss Franc': 'সুইস ফ্রাঁ',
  'Chilean Peso': 'চিলি পেসো',
  'Colombian Peso': 'কলোম্বিয়ান পেসো',
  'Costa Rican Colon': 'কোস্টা রিকা কোলোন',
  'Cuban Peso': 'কিউবান পেসো',
  'Cabo Verde Escudo': 'কেপ ভার্দে এসকুডো',
  'Czech Koruna': 'চেক প্রজাতন্ত্র কোরুনা',
  'Djiboutian Franc': 'জিবুতি ফ্রাঙ্ক',
  'Danish Krone': 'ড্যানিশ ক্রোন',
  'Dominican Peso': 'ডোমিনিকান পেসো',
  'Algerian Dinar': 'আলজেরীয় দিনার',
  'Egyptian Pound': 'মিশরীয় পাউন্ড',
  'Nakfa': 'এরিট্রিয়েন নাকফা',
  'Ethiopian Birr': 'ইথিওপিয়ান বির',
  'Fiji Dollar': 'ফিজি ডলার',
  'Falkland Islands Pound': 'ফকল্যান্ড দ্বীপপুঞ্জ পাউন্ড',
  'Lari': 'জর্জিয়ান লারি',
  'Ghana Cedi': 'ঘানা সেডি',
  'Gibraltar Pound': 'জিব্রাল্টার পাউন্ড',
  'Dalasi': 'গাম্বিয়া ডালাসি',
  'Guinean Franc': 'গিনি ফ্রাঙ্ক',
  'Quetzal': 'গুয়াতেমালা কুয়েৎজাল',
  'Guyana Dollar': 'গায়ানিজ ডলার',
  'Hong Kong Dollar': 'হংকং ডলার',
  'Lempira': 'হন্ডুরাস লেম্পিরা',
  'Gourde': 'হাইতি গৌর্দে',
  'Forint': 'হাঙ্গেরিয়ান ফোরিন্ট',
  'Rupiah': 'ইন্দোনেশিয়ান রুপিয়াহ',
  'New Israeli Sheqel': 'ইসরায়েলি নতুন শেকেল',
  'Iraqi Dinar': 'ইরাকি দিনার',
  'Iranian Rial': 'ইরানিয়ান রিয়াল',
  'Iceland Krona': 'আইসল্যান্ডীয় ক্রোনা',
  'Jamaican Dollar': 'জামাইকান ডলার',
  'Jordanian Dinar': 'জর্ডানিয়ান দিনার',
  'Kenyan Shilling': 'কেনিয়ান শিলিং',
  'Som': 'কিরগিজস্তান সোম',
  'Riel': 'কম্বোডিয়ান রিয়েল',
  'Comorian Franc': 'কমোরিয়ান ফ্রাঙ্ক',
  'North Korean Won': 'উত্তর কোরিয়ার ওন',
  'Won': 'দক্ষিণ কোরিয়ান ওন',
  'Kuwaiti Dinar': 'কুয়েতি দিনার',
  'Cayman Islands Dollar': 'কেম্যান দ্বীপপুঞ্জের ডলার',
  'Tenge': 'কাজাখাস্তানি টেঙ্গে',
  'Lao Kip': 'লেউশান কিপ',
  'Lebanese Pound': 'লেবানিজ পাউন্ড',
  'Sri Lanka Rupee': 'শ্রীলঙ্কান রুপি',
  'Liberian Dollar': 'লিবেরিয়ান ডলার',
  'Loti': 'লেসুটু লোটি',
  'Libyan Dinar': 'লিবিয়ান দিনার',
  'Moroccan Dirham': 'মোরোক্কান দিরহাম',
  'Moldovan Leu': 'মোল্ডোভান লেয়ু',
  'Malagasy Ariary': 'মাদাগাস্কার আরিয়ারি',
  'Denar': 'ম্যাসেডোনিয়ান দিনার',
  'Kyat': 'মায়ানমার কিয়াত',
  'Tugrik': 'মঙ্গোলিয়ান তুগরিক',
  'Pataca': 'ম্যাক্যাও পাটাকা',
  'Ouguiya': 'মৌরিতানিয়ান ওউগুইয়া',
  'Mauritius Rupee': 'মৌরিতানিয়ান রুপি',
  'Rufiyaa': 'মালদিভিয়ান রুফিয়া',
  'Malawi Kwacha': 'মালাউইয়ান কোয়াচা',
  'Mexican Peso': 'ম্যাক্সিকান পেসো',
  'Malaysian Ringgit': 'মালয়েশিয়ান রিঙ্গিৎ',
  'Mozambique Metical': 'মোজাম্বিক মেটিকেল',
  'Namibia Dollar': 'নামিবিয়া ডলার',
  'Naira': 'নাইজেরিয়ান নায়রা',
  'Cordoba Oro': 'নিকারাগুয়ান কর্ডোবা',
  'Norwegian Krone': 'নরওয়েজিয়ান ক্রোন',
  'Nepalese Rupee': 'নেপালি রুপি',
  'New Zealand Dollar': 'নিউজিল্যান্ড ডলার',
  'Rial Omani': 'ওমানি রিয়াল',
  'Balboa': 'পানামানিয়ান বালবোয়া',
  'Sol': 'পেরুভিয়ান সোল',
  'Kina': 'পাপুয়া নিউ গিনিয়ান কিনা',
  'Philippine Peso': 'ফিলিপাইন পেসো',
  'Pakistan Rupee': 'পাকিস্তানি রুপি',
  'Zloty': 'পোলিশ জ্লোটি',
  'Guarani': 'প্যারাগুয়ান গুয়ারানি',
  'Qatari Rial': 'কাতার রিয়াল',
  'Romanian Leu': 'রুমানিয়া লেয়ু',
  'Serbian Dinar': 'সারবিয়ান দিনার',
  'Russian Ruble': 'রাশিয়ান রুবেল',
  'Rwanda Franc': 'রুয়ান্ডান ফ্রাঙ্ক',
  'Solomon Islands Dollar': 'সলোমন দ্বীপপুঞ্জ ডলার',
  'Seychelles Rupee': 'সেয়চেল্লোইস রুপি',
  'Sudanese Pound': 'সুদানি পাউন্ড',
  'Swedish Krona': 'সুইডিশ ক্রোনা',
  'Singapore Dollar': 'সিঙ্গাপুর ডলার',
  'Saint Helena Pound': 'সেন্ট হেলেনা পাউন্ড',
  'Leone': 'সিয়েরা লিয়নের লিয়ন',
  'Somali Shilling': 'সোমালি শিলিং',
  'Surinam Dollar': 'সুরিনামিজ ডলার',
  'South Sudanese Pound': 'দক্ষিণ সুদানি পাউন্ড',
  'Dobra': 'সাও টোমে এবং প্রিন্সিপে ডোবরা',
  'El Salvador Colon': 'এল স্যালভোডোর কোলোন',
  'Syrian Pound': 'সিরিয়ান পাউন্ড',
  'Lilangeni': 'সোয়াজিল্যান্ড লিলাঙ্গেনি',
  'Baht': 'থাই বাত',
  'Somoni': 'তাজিকিস্তান সোমোনি',
  'Turkmenistan New Manat': 'তুর্কমেনিস্তান মানত',
  'Tunisian Dinar': 'তিউনেশিয়ান দিনার',
  'Pa’anga': 'টোঙ্গা পা’আঙ্গা',
  'Turkish Lira': 'তুর্কি লিরা',
  'Trinidad and Tobago Dollar': 'ত্রিনিদাদ এবং টোবাগো ডলার',
  'New Taiwan Dollar': 'নতুন তাইওয়ান ডলার',
  'Tanzanian Shilling': 'তাঞ্জনিয়া শিলিং',
  'Hryvnia': 'ইউক্রেইন হৃভনিয়া',
  'Uganda Shilling': 'উগান্ডান শিলিং',
  'Peso Uruguayo': 'উরুগুয়ে পেসো',
  'Uzbekistan Sum': 'উজবেকিস্তানি সোম',
  'Bolívar Soberano': 'ভেনিজুয়েলীয় বলিভার',
  'Dong': 'ভিয়েতনামি ডঙ্গ',
  'Vatu': 'ভানুয়াতু ভাতু',
  'Tala': 'সামোয়ান টালা',
  'Central African CFA Franc': 'মধ্য আফ্রিকান [CFA] ফ্র্যাঙ্ক',
  'East Caribbean Dollar': 'পূর্ব ক্যারাবিয়ান ডলার',
  'Caribbean Guilder': 'ক্যারিবিয়ান গিল্ডার',
  'CFA Franc BCEAO': 'পশ্চিম আফ্রিকান [CFA] ফ্র্যাঙ্ক',
  'CFP Franc': 'সিএফপি ফ্র্যাঙ্ক',
  'Yemeni Rial': 'ইয়েমেনি রিয়াল',
  'Rand': 'দক্ষিণ আফ্রিকান রেন্ড',
  'Zambian Kwacha': 'জাম্বিয়ান কওয়াচা',
  'Zimbabwe Gold': 'জিম্বাবায়েন গোল্ড',
};
