// Generated from Unicode CLDR zh currency display names, 2026-09-27.
// Source: https://github.com/unicode-org/cldr-json/tree/main/cldr-json/cldr-numbers-full/main/zh
// Unicode License V3: see shopCurrencyDataLicense in shoptrack_currency_names.dart.
// Regenerate with tool/generate_chinese_currency_names.dart.
const shopChineseCurrencyNames = <String, String>{
  'UAE Dirham': '阿联酋迪拉姆',
  'Afghani': '阿富汗尼',
  'Lek': '阿尔巴尼亚列克',
  'Armenian Dram': '亚美尼亚德拉姆',
  'Kwanza': '安哥拉宽扎',
  'Argentine Peso': '阿根廷比索',
  'Australian Dollar': '澳大利亚元',
  'Aruban Florin': '阿鲁巴弗罗林',
  'Azerbaijan Manat': '阿塞拜疆马纳特',
  'Convertible Mark': '波斯尼亚-黑塞哥维那可兑换马克',
  'Barbados Dollar': '巴巴多斯元',
  'Taka': '孟加拉塔卡',
  'Bahraini Dinar': '巴林第纳尔',
  'Burundi Franc': '布隆迪法郎',
  'Bermudian Dollar': '百慕大元',
  'Brunei Dollar': '文莱元',
  'Boliviano': '玻利维亚诺',
  'Brazilian Real': '巴西雷亚尔',
  'Bahamian Dollar': '巴哈马元',
  'Ngultrum': '不丹努尔特鲁姆',
  'Pula': '博茨瓦纳普拉',
  'Belarusian Ruble': '白俄罗斯卢布',
  'Belize Dollar': '伯利兹元',
  'Canadian Dollar': '加拿大元',
  'Congolese Franc': '刚果法郎',
  'Swiss Franc': '瑞士法郎',
  'Chilean Peso': '智利比索',
  'Yuan Renminbi': '人民币',
  'Colombian Peso': '哥伦比亚比索',
  'Costa Rican Colon': '哥斯达黎加科朗',
  'Cuban Peso': '古巴比索',
  'Cabo Verde Escudo': '佛得角埃斯库多',
  'Czech Koruna': '捷克克朗',
  'Djiboutian Franc': '吉布提法郎',
  'Danish Krone': '丹麦克朗',
  'Dominican Peso': '多米尼加比索',
  'Algerian Dinar': '阿尔及利亚第纳尔',
  'Egyptian Pound': '埃及镑',
  'Nakfa': '厄立特里亚纳克法',
  'Ethiopian Birr': '埃塞俄比亚比尔',
  'Euro': '欧元',
  'Fiji Dollar': '斐济元',
  'Falkland Islands Pound': '福克兰群岛镑',
  'Pound Sterling': '英镑',
  'Lari': '格鲁吉亚拉里',
  'Ghana Cedi': '加纳塞地',
  'Gibraltar Pound': '直布罗陀镑',
  'Dalasi': '冈比亚达拉西',
  'Guinean Franc': '几内亚法郎',
  'Quetzal': '危地马拉格查尔',
  'Guyana Dollar': '圭亚那元',
  'Hong Kong Dollar': '港元',
  'Lempira': '洪都拉斯伦皮拉',
  'Gourde': '海地古德',
  'Forint': '匈牙利福林',
  'Rupiah': '印度尼西亚卢比',
  'New Israeli Sheqel': '以色列新谢克尔',
  'Indian Rupee': '印度卢比',
  'Iraqi Dinar': '伊拉克第纳尔',
  'Iranian Rial': '伊朗里亚尔',
  'Iceland Krona': '冰岛克朗',
  'Jamaican Dollar': '牙买加元',
  'Jordanian Dinar': '约旦第纳尔',
  'Yen': '日元',
  'Kenyan Shilling': '肯尼亚先令',
  'Som': '吉尔吉斯斯坦索姆',
  'Riel': '柬埔寨瑞尔',
  'Comorian Franc': '科摩罗法郎',
  'North Korean Won': '朝鲜元',
  'Won': '韩元',
  'Kuwaiti Dinar': '科威特第纳尔',
  'Cayman Islands Dollar': '开曼元',
  'Tenge': '哈萨克斯坦坚戈',
  'Lao Kip': '老挝基普',
  'Lebanese Pound': '黎巴嫩镑',
  'Sri Lanka Rupee': '斯里兰卡卢比',
  'Liberian Dollar': '利比里亚元',
  'Loti': '莱索托洛蒂',
  'Libyan Dinar': '利比亚第纳尔',
  'Moroccan Dirham': '摩洛哥迪拉姆',
  'Moldovan Leu': '摩尔多瓦列伊',
  'Malagasy Ariary': '马达加斯加阿里亚里',
  'Denar': '马其顿第纳尔',
  'Kyat': '缅甸元',
  'Tugrik': '蒙古图格里克',
  'Pataca': '澳门币',
  'Ouguiya': '毛里塔尼亚乌吉亚',
  'Mauritius Rupee': '毛里求斯卢比',
  'Rufiyaa': '马尔代夫卢菲亚',
  'Malawi Kwacha': '马拉维克瓦查',
  'Mexican Peso': '墨西哥比索',
  'Malaysian Ringgit': '马来西亚林吉特',
  'Mozambique Metical': '莫桑比克美提卡',
  'Namibia Dollar': '纳米比亚元',
  'Naira': '尼日利亚奈拉',
  'Cordoba Oro': '尼加拉瓜科多巴',
  'Norwegian Krone': '挪威克朗',
  'Nepalese Rupee': '尼泊尔卢比',
  'New Zealand Dollar': '新西兰元',
  'Rial Omani': '阿曼里亚尔',
  'Balboa': '巴拿马巴波亚',
  'Sol': '秘鲁索尔',
  'Kina': '巴布亚新几内亚基那',
  'Philippine Peso': '菲律宾比索',
  'Pakistan Rupee': '巴基斯坦卢比',
  'Zloty': '波兰兹罗提',
  'Guarani': '巴拉圭瓜拉尼',
  'Qatari Rial': '卡塔尔里亚尔',
  'Romanian Leu': '罗马尼亚列伊',
  'Serbian Dinar': '塞尔维亚第纳尔',
  'Russian Ruble': '俄罗斯卢布',
  'Rwanda Franc': '卢旺达法郎',
  'Saudi Riyal': '沙特里亚尔',
  'Solomon Islands Dollar': '所罗门群岛元',
  'Seychelles Rupee': '塞舌尔卢比',
  'Sudanese Pound': '苏丹镑',
  'Swedish Krona': '瑞典克朗',
  'Singapore Dollar': '新加坡元',
  'Saint Helena Pound': '圣赫勒拿群岛磅',
  'Leone': '塞拉利昂新利昂',
  'Somali Shilling': '索马里先令',
  'Surinam Dollar': '苏里南元',
  'South Sudanese Pound': '南苏丹镑',
  'Dobra': '圣多美和普林西比多布拉',
  'El Salvador Colon': '萨尔瓦多科朗',
  'Syrian Pound': '叙利亚镑',
  'Lilangeni': '斯威士兰里兰吉尼',
  'Baht': '泰铢',
  'Somoni': '塔吉克斯坦索莫尼',
  'Turkmenistan New Manat': '土库曼斯坦马纳特',
  'Tunisian Dinar': '突尼斯第纳尔',
  'Pa’anga': '汤加潘加',
  'Turkish Lira': '土耳其里拉',
  'Trinidad and Tobago Dollar': '特立尼达和多巴哥元',
  'New Taiwan Dollar': '新台币',
  'Tanzanian Shilling': '坦桑尼亚先令',
  'Hryvnia': '乌克兰格里夫纳',
  'Uganda Shilling': '乌干达先令',
  'US Dollar': '美元',
  'Peso Uruguayo': '乌拉圭比索',
  'Uzbekistan Sum': '乌兹别克斯坦苏姆',
  'Bolívar Soberano': '委内瑞拉玻利瓦尔',
  'Dong': '越南盾',
  'Vatu': '瓦努阿图瓦图',
  'Tala': '萨摩亚塔拉',
  'Central African CFA Franc': '中非法郎',
  'East Caribbean Dollar': '东加勒比元',
  'Caribbean Guilder': '加勒比盾',
  'CFA Franc BCEAO': '西非法郎',
  'CFP Franc': '太平洋法郎',
  'Yemeni Rial': '也门里亚尔',
  'Rand': '南非兰特',
  'Zambian Kwacha': '赞比亚克瓦查',
  'Zimbabwe Gold': '津巴布韦金元',
};
