import 'shoptrack_currency_names.dart';

/// Modern Standard Arabic interface copy. User-authored names are not translated.
const Map<String, String> shopArabicTranslations = {
  'No Price': 'بدون سعر',
  'Close ShopTrack?': 'إغلاق شوب تراك؟',
  'Do you want to close the app?': 'هل تريد إغلاق التطبيق؟',
  'No items yet': 'لا توجد منتجات بعد',
  'Tap + to add your first item.': 'اضغط على + لإضافة أول منتج.',
  'Shopping Completed': 'اكتمل التسوق',
  'All items have been purchased.': 'تم شراء جميع المنتجات.',
  ...shopArabicCurrencyNames,
  'Date Removed': 'تم حذف التاريخ',
  'No Items': 'لا توجد منتجات',
  'Sign In With Google': 'تسجيل الدخول باستخدام Google',
  'Retry Sign In': 'إعادة محاولة تسجيل الدخول',
  'packet': 'عبوة',
  'package': 'حزمة',
  'No matching items. Try another search or filter.':
      'لا توجد منتجات مطابقة. جرّب بحثًا أو تصفية أخرى.',
  'result': 'نتيجة',
  'results': 'نتائج',
  'Could not open this shopping list.': 'تعذر فتح قائمة التسوق هذه.',
  'Please enter a name.': 'أدخل اسمًا.',
  'Could not sign out. Please try again.': 'تعذر تسجيل الخروج. حاول مجددًا.',
  'kg': 'كغ',
  'g': 'غ',
  'L': 'ل',
  'mL': 'مل',
  'pc': 'قطعة',
  'pkt': 'عبوة',
  'pkg': 'حزمة',
  'Move {count} items?': 'نقل المنتجات المحددة ({count})؟',
  'Move {count} item?': 'نقل المنتج المحدد ({count})؟',
  'Move the selected items to {list}?': 'نقل المنتجات المحددة إلى {list}؟',
  'Moved {count} items to {list}.':
      'تم نقل المنتجات المحددة ({count}) إلى {list}.',
  'Moved {count} item to {list}.': 'تم نقل المنتج المحدد ({count}) إلى {list}.',
  'Delete {count} items?': 'حذف المنتجات المحددة ({count})؟',
  'Delete {count} item?': 'حذف المنتج المحدد ({count})؟',
  'Remove the selected items from this list?':
      'حذف المنتجات المحددة من هذه القائمة؟',
  'Deleted {count} items.': 'تم حذف المنتجات المحددة ({count}).',
  'Deleted {count} item.': 'تم حذف المنتج المحدد ({count}).',
  'Restored {count} items.': 'تمت استعادة المنتجات ({count}).',
  'Restored {count} item.': 'تمت استعادة المنتج ({count}).',
  'Delete {list}?': 'حذف {list}؟',
  'This will permanently delete {count} items in this list.':
      'سيُحذف نهائيًا جميع المنتجات في هذه القائمة، وعددها {count}.',
  'This will permanently delete {count} item in this list.':
      'سيُحذف نهائيًا المنتج الموجود في هذه القائمة ({count}).',
  '{item} moved to Today’s list': 'تم نقل {item} إلى قائمة اليوم',
  '{count} selected items': 'المنتجات المحددة: {count}',
  '{count} selected item': 'المنتج المحدد: {count}',
  'A shopping session already exists for {date}. Delete that session first to move this record there.':
      'يوجد سجل تسوق بتاريخ {date} بالفعل. احذف ذلك السجل أولًا لنقل هذا السجل إلى ذلك التاريخ.',
  '{count} purchased items will be moved to Today’s list. Remaining items will be planned for the new date.':
      'ستُنقل المنتجات التي تم شراؤها، وعددها {count}، إلى قائمة اليوم. وستُخطط المنتجات المتبقية للتاريخ الجديد.',
  'Items moved to Today and {date}': 'تم نقل المنتجات إلى اليوم وإلى {date}',
  'Move this session from {from} to {to}?': 'نقل هذا السجل من {from} إلى {to}؟',
  'Moved to {date}': 'تم النقل إلى {date}',
  'Arabic': 'العربية',
  'Calendar': 'التقويم',
  'Gregorian': 'الميلادي',
  'Hijri': 'الهجري',
  'Hijri (Umm al-Qura)': 'الهجري (أم القرى)',
  'Hijri date adjustment': 'تعديل التاريخ الهجري',
  'No adjustment': 'بدون تعديل',
  'Today’s preview': 'معاينة تاريخ اليوم',
  'Uses the Umm al-Qura calendar. Dates may differ from local moon-sighting announcements.':
      'يستخدم تقويم أم القرى. قد تختلف التواريخ عن الإعلانات المحلية لرؤية الهلال.',
  'Adjust the Hijri date to match your local moon-sighting announcement.':
      'عدّل التاريخ الهجري ليتوافق مع الإعلان المحلي لرؤية الهلال.',
  'This changes calendar labels, not your saved shopping dates.':
      'يغيّر هذا طريقة عرض التواريخ فقط، ولا يغيّر أيام التسوق المحفوظة.',
  'Could not save the calendar preference.': 'تعذر حفظ تفضيل التقويم.',
  'Changing language…': 'جارٍ تغيير اللغة…',
  'Please wait while ShopTrack updates the interface.':
      'يرجى الانتظار بينما يحدّث ShopTrack الواجهة.',
  '{count} days': 'عدد الأيام: {count}',
  'Calendar and language are independent.':
      'يمكن اختيار التقويم واللغة بشكل مستقل.',
  'Gregorian date': 'التاريخ الميلادي',
  'Hijri date': 'التاريخ الهجري',
  '1,234,567 · 1.23M': '١٬٢٣٤٬٥٦٧ · ١٫٢٣M',
  '12,34,567 · 12.34 Lakh': '١٢٬٣٤٬٥٦٧ · ١٢٫٣٤ لاك',
  'Select item': 'تحديد المنتج',
  'Mark as purchased': 'وضع علامة تم الشراء',
  'Select Date': 'اختيار التاريخ',
  'Date out of range': 'التاريخ خارج النطاق المسموح',
  'Enter a valid day, month and year.': 'أدخل يومًا وشهرًا وسنة صحيحة.',
  'Failed to authorize Google Drive access.':
      'تعذر الحصول على إذن الوصول إلى Google Drive.',
  'Start Date': 'تاريخ البداية',
  'End Date': 'تاريخ النهاية',
  'Previous 7 Days': 'الأيام السبعة السابقة',
  'Previous 30 Days': 'الأيام الثلاثون السابقة',
  'Last 3 Months': 'الأشهر الثلاثة الماضية',
  'This Year': 'هذه السنة',
  'Last Year': 'السنة الماضية',
  'Enter a valid date (2000–2100).': 'أدخل تاريخًا صحيحًا (٢٠٠٠–٢١٠٠).',
  'End date must be on or after start date.':
      'يجب ألا يسبق تاريخ النهاية تاريخ البداية.',
  'Use your device setting or keep ShopTrack in light or dark mode.':
      'اتبع إعدادات الجهاز، أو اختر الوضع الفاتح أو الداكن في ShopTrack.',
  'Choose the scenery used in light mode.': 'اختر خلفية الوضع الفاتح.',
  'Choose the scenery used in dark mode.': 'اختر خلفية الوضع الداكن.',
  'Local': 'ملف',
  'Cloud': 'السحابة',
  'LOCAL BACKUP': 'نسخ احتياطي إلى ملف',
  'LOCAL RESTORE': 'استعادة من ملف',
  'CLOUD BACKUP': 'نسخ احتياطي سحابي',
  'CLOUD RESTORE': 'استعادة من السحابة',
  'Last backup': 'آخر نسخة احتياطية',
  'Save a separate backup in Google Drive. This is not automatic Cloud Sync.':
      'احفظ نسخة احتياطية منفصلة في Google Drive. هذه ليست المزامنة السحابية التلقائية.',
  'Saved on This Device': 'محفوظ على هذا الجهاز',
  'Saving Changes': 'جارٍ حفظ التغييرات',
  'All Changes Saved': 'تم حفظ جميع التغييرات',
  'Sync Needs Attention': 'المزامنة تتطلب المراجعة',
  'A local save failed. Keep the app open and try again.':
      'تعذر الحفظ على هذا الجهاز. أبقِ التطبيق مفتوحًا وحاول مجددًا.',
  'Some edits need your review. Both versions have been kept.':
      'تحتاج بعض التعديلات إلى مراجعتك. تم الاحتفاظ بالنسختين.',
  'Sign in to sync. These lists stay with their original account.':
      'سجّل الدخول للمزامنة. تظل هذه القوائم مرتبطة بحسابها الأصلي.',
  'Waiting for the cloud. Changes will upload automatically when a connection is available.':
      'بانتظار الاتصال بالسحابة. ستُرفع التغييرات تلقائيًا عند توفر الاتصال.',
  'Your shopping lists and history sync automatically while ShopTrack is open.':
      'تُزامَن قوائم التسوق والسجل تلقائيًا أثناء فتح ShopTrack وتوفر اتصال بالإنترنت.',
  'Cloud saving is paused. Your changes remain on this device. Try again shortly.':
      'الحفظ السحابي متوقف مؤقتًا. تبقى تغييراتك على هذا الجهاز. حاول مجددًا بعد قليل.',
  'Last uploaded from this device': 'آخر رفع من هذا الجهاز',
  'Shopping data in your account': 'بيانات التسوق في حسابك',
  'Lists, items, prices and purchase history sync to your signed-in account while the app is open and online.':
      'تُزامَن القوائم والمنتجات والأسعار وسجل المشتريات مع الحساب المسجّل دخوله أثناء فتح التطبيق واتصاله بالإنترنت.',
  'Settings kept on this device': 'إعدادات محفوظة على هذا الجهاز',
  'Appearance and your ShopTrack profile stay on this device; automatic sync does not copy them to other devices.':
      'تبقى إعدادات المظهر وملفك الشخصي في ShopTrack على هذا الجهاز؛ ولا تنقلها المزامنة التلقائية إلى أجهزة أخرى.',
  'Continue on another device': 'المتابعة على جهاز آخر',
  'Open ShopTrack and sign in to the same account to load your synced shopping data.':
      'افتح ShopTrack وسجّل الدخول بالحساب نفسه للوصول إلى بيانات التسوق التي تمت مزامنتها.',
  'Lists': 'القوائم',
  'History': 'السجل',
  'Profile': 'الملف الشخصي',
  'Today': 'اليوم',
  'TODAY': 'اليوم',
  'UPCOMING': 'القادم',
  'To Buy': 'للشراء',
  'Purchased': 'تم الشراء',
  'Planned': 'مخطط له',
  'Pending': 'لم يُشترَ بعد',
  'Total Amount': 'المبلغ الإجمالي',
  'Purchased Amount': 'إجمالي المشتريات',
  'Total Purchased': 'إجمالي المشتريات',
  'Add Item': 'إضافة منتج',
  'Add item': 'إضافة منتج',
  'Edit Item': 'تعديل المنتج',
  'New Date': 'تاريخ جديد',
  'Create a past or future date': 'إضافة تاريخ سابق أو قادم',
  'Share Your List': 'مشاركة القائمة',
  'Share': 'مشاركة',
  'Copy Text': 'نسخ النص',
  'Copy or Share': 'نسخ أو مشاركة',
  'More actions': 'إجراءات إضافية',
  'Cancel': 'إلغاء',
  'Save': 'حفظ',
  'Save Changes': 'حفظ التغييرات',
  'Delete': 'حذف',
  'Delete List': 'حذف القائمة',
  'Delete Permanently': 'حذف نهائي',
  'Move': 'نقل',
  'Remove': 'إزالة',
  'Edit': 'تعديل',
  'Create': 'إنشاء',
  'Clear': 'مسح',
  'Apply Range': 'تطبيق النطاق',
  'Try Again': 'إعادة المحاولة',
  'OK': 'موافق',
  'Quantity': 'الكمية',
  'Unit': 'الوحدة',
  'No Unit': 'بلا وحدة',
  'Price basis': 'أساس التسعير',
  'Currency': 'العملة',
  'Total Price': 'السعر الإجمالي',
  'Price per Unit': 'سعر الوحدة',
  'Notes': 'ملاحظات',
  'Item Name': 'اسم المنتج',
  'Often Bought': 'منتجات متكررة الشراء',
  'Frequently Purchased': 'منتجات متكررة الشراء',
  'Fewer Options': 'خيارات أقل',
  'More Options': 'خيارات إضافية',
  'Search history': 'البحث في السجل',
  'Search History': 'البحث في السجل',
  'Date Range': 'النطاق الزمني',
  'Select Date Range': 'اختيار النطاق الزمني',
  'Past Date': 'تاريخ سابق',
  'Future Date': 'تاريخ قادم',
  'Edit Date': 'تعديل التاريخ',
  'Edit Shopping Date': 'تعديل تاريخ التسوق',
  'Date Already Exists': 'التاريخ موجود بالفعل',
  'Purchased items detected': 'توجد منتجات تم شراؤها',
  'Change Shopping Date?': 'تغيير تاريخ التسوق؟',
  'Move Date': 'نقل التاريخ',
  'Continue': 'متابعة',
  'Purchased items stay in Today. No future session created.':
      'تبقى المنتجات التي تم شراؤها في قائمة اليوم. لم يُنشأ سجل لتاريخ قادم.',
  'All items moved to Today': 'تم نقل جميع المنتجات إلى اليوم',
  'Add Shopping Date': 'إضافة تاريخ تسوق',
  'Create shopping date?': 'إنشاء تاريخ تسوق؟',
  'No shopping history yet': 'لا يوجد سجل تسوق بعد',
  'No items added': 'لم تُضف أي منتجات',
  'A list with that name already exists.': 'توجد قائمة بهذا الاسم بالفعل.',
  'Rename List': 'إعادة تسمية القائمة',
  'Delete item?': 'حذف المنتج؟',
  'Are you sure you want to delete this item?': 'هل تريد حذف هذا المنتج؟',
  'Delete this date?': 'حذف هذا التاريخ؟',
  'This permanently deletes this shopping record and every list inside it.':
      'سيُحذف سجل التسوق هذا وجميع قوائمه نهائيًا.',
  'This will permanently delete this shopping record and all of its items. This action cannot be undone.':
      'سيُحذف سجل التسوق هذا وجميع منتجاته نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
  'You must add at least one item for this date to be saved.':
      'أضف منتجًا واحدًا على الأقل لحفظ هذا التاريخ.',
  'Stay Here': 'البقاء هنا',
  'Discard & Go Back': 'تجاهل والرجوع',
  'Discard Changes?': 'تجاهل التغييرات؟',
  'Your profile has not been saved.': 'لم تُحفظ تغييرات ملفك الشخصي.',
  'Keep Editing': 'متابعة التعديل',
  'Discard': 'تجاهل',
  'All Lists': 'جميع القوائم',
  'Choose one or more lists': 'اختر قائمة واحدة أو أكثر',
  'Select at least one list.': 'اختر قائمة واحدة على الأقل.',
  'Add an item before sharing this list.': 'أضف منتجًا قبل مشاركة هذه القائمة.',
  'Shopping list copied.': 'تم نسخ قائمة التسوق.',
  'Could not copy this list. Please try again.':
      'تعذر نسخ القائمة. حاول مجددًا.',
  'Could not share this list. Please try again.':
      'تعذرت مشاركة القائمة. حاول مجددًا.',
  'Failed to create local backup': 'تعذر إنشاء نسخة احتياطية في ملف',
  'Failed to restore local backup': 'تعذرت استعادة النسخة الاحتياطية من الملف',
  'Cloud backup failed': 'تعذر النسخ الاحتياطي السحابي',
  'Cloud restore failed': 'تعذرت الاستعادة من السحابة',
  'No matching currency': 'لا توجد عملة مطابقة',
  'Try its three-letter code or full name.':
      'ابحث برمز العملة المكوّن من ثلاثة أحرف أو باسمها الكامل.',
  'Default Currency': 'العملة الافتراضية',
  'Choose Currency': 'اختيار العملة',
  'Search by code or currency name': 'ابحث برمز العملة أو اسمها',
  'Recent': 'مستخدمة مؤخرًا',
  'default': 'افتراضية',
  'recent': 'مستخدمة مؤخرًا',
  '(default)': '(افتراضية)',
  'Appearance': 'المظهر',
  'My List': 'قائمتي',
  "Today's Shopping": 'تسوق اليوم',
  'TO BUY': 'للشراء',
  'PURCHASED': 'تم الشراء',
  'SELECTED ITEMS': 'المنتجات المحددة',
  'ALL LISTS': 'جميع القوائم',
  'Note': 'ملاحظة',
  'total': 'الإجمالي',
  'totals': 'الإجماليات',
  'No items yet.': 'لا توجد منتجات بعد.',
  'All': 'الكل',
  'This empty list will be deleted.': 'ستُحذف هذه القائمة الفارغة.',
  'This record changed elsewhere. Both versions are kept; review them in Profile → Cloud Sync.':
      'تم تعديل هذا السجل على جهاز آخر. تم الاحتفاظ بالنسختين؛ راجعهما في الملف الشخصي ← المزامنة السحابية.',
  'This record changed elsewhere. Review changes in Profile → Cloud Sync.':
      'تم تعديل هذا السجل على جهاز آخر. راجع التغييرات في الملف الشخصي ← المزامنة السحابية.',
  'Move undone.': 'تم التراجع عن النقل.',
  'Could not open this shopping list. Your data is still on this device.':
      'تعذر فتح قائمة التسوق. لا تزال بياناتك محفوظة على هذا الجهاز.',
  'Could not undo the move. The items or lists may have changed; your latest data is kept.':
      'تعذر التراجع عن النقل. ربما تغيرت المنتجات أو القوائم؛ تم الاحتفاظ بأحدث بياناتك.',
  'Could not undo the deletion because this list changed. Your latest data is kept.':
      'تعذر التراجع عن الحذف لأن القائمة تغيرت. تم الاحتفاظ بأحدث بياناتك.',
  'Could not save this change. Your selection is kept; please try again.':
      'تعذر حفظ التغيير. تم الاحتفاظ بتحديدك؛ حاول مجددًا.',
  'Create List': 'إنشاء قائمة',
  'Preferences': 'التفضيلات',
  'Account & Data': 'الحساب والبيانات',
  'Language': 'اللغة',
  'Language Preference': 'اختيار اللغة',
  'English': 'الإنجليزية',
  'Bangla': 'البنغالية',
  'Number Format': 'تنسيق الأرقام',
  'Automatic': 'تلقائي',
  'International': 'دولي',
  'South Asian': 'جنوب آسيوي',
  'Match each currency’s region': 'وفق تنسيق منطقة كل عملة',
  'Follow your device region': 'وفق منطقة الجهاز',
  'System': 'النظام',
  'Light': 'فاتح',
  'Dark': 'داكن',
  'Edit Profile': 'تعديل الملف الشخصي',
  'Change Photo': 'تغيير الصورة',
  'Choose From Gallery': 'اختيار من المعرض',
  'Remove Photo': 'إزالة الصورة',
  'Google Account': 'حساب Google',
  'Email cannot be edited here.': 'لا يمكن تعديل البريد الإلكتروني هنا.',
  'Saved on this device. Your Google account name and photo stay unchanged.':
      'يُحفظ على هذا الجهاز. لن يتغير اسم حساب Google أو صورته.',
  'Your saved profile could not be loaded. Please restart the app.':
      'تعذر تحميل ملفك الشخصي المحفوظ. أعد تشغيل التطبيق.',
  'Sign In Required': 'يلزم تسجيل الدخول',
  'Sign in Required': 'يلزم تسجيل الدخول',
  'Sign In': 'تسجيل الدخول',
  'Sign In with Google': 'تسجيل الدخول باستخدام Google',
  'Sign Out': 'تسجيل الخروج',
  'Sign Out?': 'تسجيل الخروج؟',
  'Your lists stay accessible on this device. Cloud sync pauses until you sign back into the same account.\n\nCloud data and backups are kept. Other accounts have separate history.':
      'تظل قوائمك متاحة على هذا الجهاز. تتوقف المزامنة السحابية مؤقتًا حتى تسجّل الدخول مجددًا بالحساب نفسه.\n\nيُحتفظ بالبيانات السحابية والنسخ الاحتياطية. لكل حساب آخر سجل مستقل.',
  'You need to sign in with your Google account to use cloud backup and synchronization features.':
      'سجّل الدخول بحساب Google لاستخدام النسخ الاحتياطي السحابي والمزامنة.',
  'You need to sign in with your Google account to use cloud backup features.':
      'سجّل الدخول بحساب Google لاستخدام النسخ الاحتياطي السحابي.',
  'Cloud Sync': 'المزامنة السحابية',
  'Retry Sync': 'إعادة محاولة المزامنة',
  'Review Changes': 'مراجعة التغييرات',
  'The same record changed in two places. Review both versions before choosing. Other edits can continue syncing.':
      'تم تعديل السجل نفسه على جهازين. راجع النسختين قبل الاختيار. يمكن مواصلة مزامنة التعديلات الأخرى.',
  'This is part of an item transfer. Your choice applies to both related dates below.':
      'هذا جزء من نقل المنتجات. سيُطبَّق اختيارك على التاريخين المرتبطين أدناه.',
  'This Device': 'هذا الجهاز',
  'Saved Version': 'النسخة المحفوظة',
  'Keep Saved Version': 'الاحتفاظ بالنسخة المحفوظة',
  'Use My Changes': 'استخدام تعديلاتي',
  'Advanced Backup & Restore': 'خيارات النسخ الاحتياطي والاستعادة',
  'File and Google Drive backups': 'نسخ احتياطية في ملفات وGoogle Drive',
  'Backup & Restore': 'النسخ الاحتياطي والاستعادة',
  'Restore Backup?': 'استعادة النسخة الاحتياطية؟',
  'Restoring this backup will replace your current local ShopTrack data. If cloud sync is enabled, these changes also sync to this account’s other devices. Export a backup first if you want to keep the current version.':
      'ستحل هذه النسخة الاحتياطية محل بيانات ShopTrack الحالية على الجهاز. إذا كانت المزامنة السحابية مفعّلة، فستُزامَن التغييرات أيضًا مع أجهزة هذا الحساب الأخرى. صدّر نسخة احتياطية أولًا إذا أردت الاحتفاظ بالنسخة الحالية.',
  'Restore': 'استعادة',
  'Data restored successfully': 'تمت استعادة البيانات',
  'Local backup created successfully': 'تم إنشاء النسخة الاحتياطية في ملف',
  'No backup found in your cloud storage.':
      'لم يُعثر على نسخة احتياطية في التخزين السحابي.',
  'Could not save your choice. Please try again.':
      'تعذر حفظ اختيارك. حاول مجددًا.',
  'Could not save the currency preference.': 'تعذر حفظ العملة المفضلة.',
  'Could not save the language preference.': 'تعذر حفظ اللغة المفضلة.',
  'Cloud Backup': 'النسخ الاحتياطي السحابي',
  'Back up to your Google account': 'نسخ احتياطي إلى حساب Google',
  'Sign in to enable cloud backup':
      'سجّل الدخول لتفعيل النسخ الاحتياطي السحابي',
  'Lists stay on this device': 'تبقى القوائم على هذا الجهاز',
  'Your Profile': 'ملفك الشخصي',
  'Welcome to ShopTrack': 'مرحبًا بك في ShopTrack',
  'Sign in with Google to use cloud backup.':
      'سجّل الدخول باستخدام Google للنسخ الاحتياطي السحابي.',
  'Could not save this change. Please try again.':
      'تعذر حفظ التغيير. حاول مجددًا.',
  'Could not move this item. Please try again.':
      'تعذر نقل المنتج. حاول مجددًا.',
  'Item deleted': 'تم حذف المنتج',
  'Item saved, but the recent currency shortcut could not be updated.':
      'تم حفظ المنتج، لكن تعذر تحديث اختصار العملة المستخدمة مؤخرًا.',
  'About ShopTrack': 'حول ShopTrack',
  'Your Shopping Companion': 'رفيقك في التسوق',
  'Plan your shopping, track purchases and keep your history close—even offline.':
      'خطط لتسوقك، وتابع مشترياتك، واحتفظ بسجلك في متناولك حتى دون اتصال بالإنترنت.',
  'App Version': 'إصدار التطبيق',
  '© 2026 ShopTrack Team': '© ٢٠٢٦ فريق ShopTrack',
  'Stay organized. Shop smarter.': 'نظّم قوائمك. تسوّق بذكاء.',
  'Find items across your shopping dates':
      'ابحث عن المنتجات في جميع تواريخ التسوق',
  'Close': 'إغلاق',
  'Back': 'رجوع',
  'Back to History': 'العودة إلى السجل',
  'Day': 'اليوم',
  'Month': 'الشهر',
  'Year': 'السنة',
  'Search currencies': 'البحث عن العملات',
  'Clear search': 'مسح البحث',
  'Search items': 'البحث عن المنتجات',
  'e.g. Eggs': 'مثل: بيض',
  'e.g. Household': 'مثل: مستلزمات المنزل',
  'e.g. Grandmother': 'مثل: الجدة',
  'List name': 'اسم القائمة',
  'New shopping list': 'قائمة تسوق جديدة',
  'Rename shopping list': 'إعادة تسمية قائمة التسوق',
  'Move to List': 'نقل إلى قائمة',
  'Choose where the selected items should go.':
      'اختر القائمة التي تريد نقل المنتجات المحددة إليها.',
  'No other lists yet': 'لا توجد قوائم أخرى بعد',
  'Create another list, then move these items into it.':
      'أنشئ قائمة أخرى، ثم انقل هذه المنتجات إليها.',
  'Undo': 'تراجع',
  'Manage this shopping list.': 'إدارة قائمة التسوق هذه.',
  'Cancel Selection': 'إلغاء التحديد',
  'Select All': 'تحديد الكل',
  'Deselect All': 'إلغاء تحديد الكل',
  'Selected': 'محدد',
  'Item': 'منتج',
  'Items': 'منتجات',
  'item': 'منتج',
  'items': 'منتجات',
  'list': 'قائمة',
  'lists': 'قوائم',
  'Copy or Share Selected Items': 'نسخ المنتجات المحددة أو مشاركتها',
  'Date options': 'خيارات التاريخ',
  'Previous month': 'الشهر السابق',
  'Next month': 'الشهر التالي',
  'Add an earlier record or plan a future trip.':
      'أضف سجلًا سابقًا أو خطط لتسوق قادم.',
  'Choose Theme': 'اختيار السمة',
  'Light Theme': 'السمة الفاتحة',
  'Dark Theme': 'السمة الداكنة',
  'Golden Summer': 'الصيف الذهبي',
  'Blooming Spring': 'الربيع المزهر',
  'Tranquil Ocean': 'المحيط الهادئ',
  'Ember Autumn': 'وهج الخريف',
  'Silent Midnight': 'سكون منتصف الليل',
  'Ethereal Aurora': 'الشفق الساحر',
  'Bleeding Moonlight': 'ضوء القمر القرمزي',
  'Ancient Forest': 'الغابة العتيقة',
  'Profile Photo': 'صورة الملف الشخصي',
  'Choose how your profile appears in ShopTrack.':
      'اختر مظهر ملفك الشخصي في ShopTrack.',
  'Display Name': 'الاسم المعروض',
  'Only used in ShopTrack': 'يُستخدم في ShopTrack فقط',
  'Create Local Backup': 'إنشاء نسخة احتياطية في ملف',
  'Export your data to a JSON file': 'تصدير بياناتك إلى ملف JSON',
  'Restore from Local File': 'استعادة من ملف محلي',
  'Select a previously saved JSON backup':
      'اختيار نسخة احتياطية محفوظة بصيغة JSON',
  'Back up to Cloud': 'نسخ احتياطي إلى السحابة',
  'Sync your data to Google Drive App Data':
      'حفظ بياناتك في مساحة بيانات التطبيق في Google Drive',
  'Restore from Cloud': 'استعادة من السحابة',
  'Download your latest cloud backup': 'تنزيل أحدث نسخة احتياطية سحابية',
  'Synced': 'تمت المزامنة',
  'Lists, items, prices, quantities and history.':
      'القوائم والمنتجات والأسعار والكميات والسجل.',
  'On This Device': 'على هذا الجهاز',
  'Appearance and your ShopTrack profile.': 'المظهر وملفك الشخصي في ShopTrack.',
  'Use Another Device': 'الاستخدام على جهاز آخر',
  'Sign in to the same account to load your lists.':
      'سجّل الدخول بالحساب نفسه للوصول إلى قوائمك.',
  'Kilogram (kg)': 'كيلوغرام (kg)',
  'Gram (g)': 'غرام (g)',
  'Litre (L)': 'لتر (L)',
  'Millilitre (mL)': 'مليلتر (mL)',
  'Piece (pc)': 'قطعة',
  'Packet': 'عبوة',
  'Package': 'حزمة',
  'Item name is required': 'أدخل اسم المنتج',
  'Unit required for Price per Unit': 'اختر وحدة لتحديد سعر الوحدة',
  'Last used price': 'آخر سعر مستخدم',
  'Double tap to change currency': 'اضغط مرتين لتغيير العملة',
  'Price per': 'السعر لكل',
  'Taka': 'تاكا بنغلاديشية',
  'US Dollar': 'دولار أمريكي',
  'Euro': 'يورو',
  'Pound Sterling': 'جنيه إسترليني',
  'Saudi Riyal': 'ريال سعودي',
  'UAE Dirham': 'درهم إماراتي',
  'Yen': 'ين ياباني',
  'Yuan Renminbi': 'يوان صيني',
  'Indian Rupee': 'روبية هندية',
  'Price per unit': 'سعر الوحدة',
  'Total': 'الإجمالي',
  'This quantity cannot be saved exactly.': 'لا يمكن حفظ هذه الكمية بدقة.',
  'Enter an exact price with up to 2 decimals.':
      'أدخل سعرًا دقيقًا بما لا يزيد على منزلتين عشريتين.',
  'This total cannot be saved exactly.':
      'لا يمكن حفظ هذا المبلغ الإجمالي بدقة.',
};
