import 'shoptrack_chinese_currency_names.dart';

/// Simplified Chinese interface copy. Never translate user-authored names.
const shopChineseTranslations = <String, String>{
  ...shopChineseCurrencyNames,
  'Chinese': '简体中文',
  'No Price': '未填写价格',
  'No Date Range Selected': '尚未选择日期范围',
  'Close ShopTrack?': '退出 ShopTrack？',
  'Do you want to close the app?': '确定要退出应用吗？',
  'No items yet': '暂无商品',
  'Tap + to add your first item.': '点击 + 添加第一件商品。',
  'Shopping Completed': '采购完成',
  'All items have been purchased.': '所有商品均已购买。',
  'Date Removed': '记录已删除',
  'No Items': '暂无商品',
  'Sign In With Google': '使用 Google 登录',
  'Retry Sign In': '重新登录',
  'packet': '包',
  'package': '包装',
  'No matching items. Try another search or filter.': '未找到匹配的商品，请更换关键词或筛选条件。',
  'result': '条结果',
  'results': '条结果',
  'Could not open this shopping list.': '无法打开此购物清单。',
  'Please enter a name.': '请输入名称。',
  'Could not sign out. Please try again.': '无法退出登录，请重试。',
  'kg': '千克',
  'g': '克',
  'L': '升',
  'mL': '毫升',
  'pc': '件',
  'pkt': '包',
  'pkg': '包装',
  'Move {count} items?': '移动 {count} 件商品？',
  'Move {count} item?': '移动 {count} 件商品？',
  'Move the selected items to {list}?': '将所选商品移至「{list}」？',
  'Moved {count} items to {list}.': '已将 {count} 件商品移至「{list}」。',
  'Moved {count} item to {list}.': '已将 {count} 件商品移至「{list}」。',
  'Delete {count} items?': '删除 {count} 件商品？',
  'Delete {count} item?': '删除 {count} 件商品？',
  'Remove the selected items from this list?': '从此清单中删除所选商品？',
  'Deleted {count} items.': '已删除 {count} 件商品。',
  'Deleted {count} item.': '已删除 {count} 件商品。',
  'Restored {count} items.': '已恢复 {count} 件商品。',
  'Restored {count} item.': '已恢复 {count} 件商品。',
  'Delete {list}?': '删除「{list}」？',
  'This will permanently delete {count} items in this list.':
      '这将永久删除此清单中的 {count} 件商品。',
  'This will permanently delete {count} item in this list.':
      '这将永久删除此清单中的 {count} 件商品。',
  '{item} moved to Today’s list': '已将「{item}」移至今日清单',
  '{count} selected items': '已选 {count} 件商品',
  '{count} selected item': '已选 {count} 件商品',
  'A shopping session already exists for {date}. Delete that session first to move this record there.':
      '{date} 已有购物记录。请先删除该记录，再将此记录移至该日期。',
  '{count} purchased items will be moved to Today’s list. Remaining items will be planned for the new date.':
      '{count} 件已购商品将移至今日清单，其余商品将安排至新日期。',
  'Items moved to Today and {date}': '商品已分别移至今日和 {date}',
  'Move this session from {from} to {to}?': '将此购物记录从 {from} 移至 {to}？',
  'Moved to {date}': '已移至 {date}',
  'Arabic': '阿拉伯语',
  'Calendar': '日历',
  'Gregorian': '公历',
  'Hijri': '伊斯兰历',
  'Hijri (Umm al-Qura)': '伊斯兰历（乌姆古拉历）',
  'Hijri date adjustment': '伊斯兰历日期校正',
  'No adjustment': '不校正',
  'Today’s preview': '今日日期预览',
  'Uses the Umm al-Qura calendar. Dates may differ from local moon-sighting announcements.':
      '采用乌姆古拉历，日期可能与当地观月公告不同。',
  'Adjust the Hijri date to match your local moon-sighting announcement.':
      '根据当地观月公告校正伊斯兰历日期。',
  'This changes calendar labels, not your saved shopping dates.':
      '仅更改日期显示，不会改变已保存的购物日期。',
  'Could not save the calendar preference.': '无法保存日历设置。',
  'Changing language…': '正在切换语言…',
  'Please wait while ShopTrack updates the interface.': 'ShopTrack 正在更新界面，请稍候。',
  '{count} days': '{count} 天',
  'Calendar and language are independent.': '日历与语言可分别设置。',
  'Gregorian date': '公历日期',
  'Hijri date': '伊斯兰历日期',
  '1,234,567 · 1.23M': '1,234,567 · 1.23M',
  '12,34,567 · 12.34 Lakh': '12,34,567 · 12.34 Lakh',
  'Select item': '选择商品',
  'Mark as purchased': '标记为已购买',
  'Select Date': '选择日期',
  'Date out of range': '日期超出范围',
  'Enter a valid day, month and year.': '请输入有效的年、月、日。',
  'Failed to authorize Google Drive access.': '无法授权访问 Google 云端硬盘。',
  'Start Date': '开始日期',
  'End Date': '结束日期',
  'Previous 7 Days': '过去 7 天',
  'Previous 30 Days': '过去 30 天',
  'Last 3 Months': '过去 3 个月',
  'This Year': '今年',
  'Last Year': '去年',
  'Enter a valid date (2000–2100).': '请输入有效日期（2000—2100 年）。',
  'End date must be on or after start date.': '结束日期不能早于开始日期。',
  'Use your device setting or keep ShopTrack in light or dark mode.':
      '跟随系统设置，或让 ShopTrack 始终使用浅色或深色模式。',
  'Choose the scenery used in light mode.': '选择浅色模式的背景风景。',
  'Choose the scenery used in dark mode.': '选择深色模式的背景风景。',
  'Local': '本机',
  'Cloud': '云端',
  'LOCAL BACKUP': '本机备份',
  'LOCAL RESTORE': '从本机恢复',
  'CLOUD BACKUP': '云端备份',
  'CLOUD RESTORE': '从云端恢复',
  'Last backup': '上次备份',
  'Save a separate backup in Google Drive. This is not automatic Cloud Sync.':
      '在 Google 云端硬盘中另存一份备份，此功能与自动云同步不同。',
  'Saved on This Device': '已保存到本机',
  'Saving Changes': '正在保存更改',
  'All Changes Saved': '所有更改已保存',
  'Sync Needs Attention': '同步需要处理',
  'A local save failed. Keep the app open and try again.': '本机保存失败，请保持应用打开并重试。',
  'Some edits need your review. Both versions have been kept.':
      '部分更改需要您确认，两个版本均已保留。',
  'Sign in to sync. These lists stay with their original account.':
      '登录后即可同步，这些清单仍归原账号所有。',
  'Waiting for the cloud. Changes will upload automatically when a connection is available.':
      '正在等待连接云端，网络恢复后将自动上传更改。',
  'Your shopping lists and history sync automatically while ShopTrack is open.':
      'ShopTrack 打开时会自动同步购物清单和历史记录。',
  'Cloud saving is paused. Your changes remain on this device. Try again shortly.':
      '云端保存已暂停，更改仍保留在本机，请稍后重试。',
  'Last uploaded from this device': '本机上次上传时间',
  'Shopping data in your account': '账号中的购物数据',
  'Lists, items, prices and purchase history sync to your signed-in account while the app is open and online.':
      '应用打开且联网时，清单、商品、价格和购买记录会同步至当前登录的账号。',
  'Settings kept on this device': '仅保存在本机的设置',
  'Appearance and your ShopTrack profile stay on this device; automatic sync does not copy them to other devices.':
      '外观设置和 ShopTrack 个人资料仅保存在本机，不会自动同步到其他设备。',
  'Continue on another device': '在其他设备上继续使用',
  'Open ShopTrack and sign in to the same account to load your synced shopping data.':
      '在其他设备上打开 ShopTrack 并登录同一账号，即可获取已同步的购物数据。',
  'Lists': '清单',
  'History': '历史记录',
  'Profile': '个人中心',
  'Today': '今天',
  'TODAY': '今天',
  'UPCOMING': '即将到来',
  'To Buy': '待购买',
  'Purchased': '已购买',
  'Planned': '已计划',
  'Pending': '待购买',
  'Total Amount': '总金额',
  'Purchased Amount': '已购总金额',
  'Total Purchased': '已购总金额',
  'Add Item': '添加商品',
  'Add item': '添加商品',
  'Edit Item': '编辑商品',
  'New Date': '添加日期',
  'Create a past or future date': '添加过去或未来的购物日期',
  'Share Your List': '分享清单',
  'Share': '分享',
  'Copy Text': '复制文本',
  'Copy or Share': '复制或分享',
  'More actions': '更多操作',
  'Cancel': '取消',
  'Save': '保存',
  'Save Changes': '保存更改',
  'Delete': '删除',
  'Delete List': '删除清单',
  'Delete Permanently': '永久删除',
  'Move': '移动',
  'Remove': '移除',
  'Edit': '编辑',
  'Create': '创建',
  'Clear': '清除',
  'Apply Range': '应用范围',
  'Try Again': '重试',
  'OK': '确定',
  'Quantity': '数量',
  'Unit': '单位',
  'No Unit': '无单位',
  'Price basis': '计价单位',
  'Currency': '货币',
  'Total Price': '总价',
  'Price per Unit': '单价',
  'Notes': '备注',
  'Item Name': '商品名称',
  'Often Bought': '常购商品',
  'Frequently Purchased': '常购商品',
  'Fewer Options': '收起选项',
  'More Options': '更多选项',
  'Search history': '搜索历史记录',
  'Search History': '搜索历史记录',
  'Date Range': '日期范围',
  'Select Date Range': '选择日期范围',
  'Past Date': '过去日期',
  'Future Date': '未来日期',
  'Edit Date': '编辑日期',
  'Edit Shopping Date': '编辑购物日期',
  'Date Already Exists': '日期已存在',
  'Purchased items detected': '包含已购商品',
  'Change Shopping Date?': '更改购物日期？',
  'Move Date': '移动日期',
  'Continue': '继续',
  'Purchased items stay in Today. No future session created.':
      '已购商品保留在今日清单中，未创建未来的购物记录。',
  'All items moved to Today': '所有商品已移至今日清单',
  'Add Shopping Date': '添加购物日期',
  'Create shopping date?': '创建购物日期？',
  'No shopping history yet': '暂无购物记录',
  'No items added': '尚未添加商品',
  'A list with that name already exists.': '已存在同名清单。',
  'Rename List': '重命名清单',
  'Delete item?': '删除商品？',
  'Are you sure you want to delete this item?': '确定要删除此商品吗？',
  'Delete this date?': '删除此日期的记录？',
  'This permanently deletes this shopping record and every list inside it.':
      '这将永久删除此购物记录及其中的所有清单。',
  'This will permanently delete this shopping record and all of its items. This action cannot be undone.':
      '这将永久删除此购物记录及所有商品，操作无法撤销。',
  'You must add at least one item for this date to be saved.':
      '至少添加一件商品才能保存此日期。',
  'Stay Here': '留在此页',
  'Discard & Go Back': '放弃并返回',
  'Discard Changes?': '放弃更改？',
  'Your profile has not been saved.': '您的个人资料尚未保存。',
  'Keep Editing': '继续编辑',
  'Discard': '放弃',
  'All Lists': '所有清单',
  'Choose one or more lists': '选择一个或多个清单',
  'Select at least one list.': '请至少选择一个清单。',
  'Add an item before sharing this list.': '请先添加商品，再分享此清单。',
  'Shopping list copied.': '购物清单已复制。',
  'Could not copy this list. Please try again.': '无法复制此清单，请重试。',
  'Could not share this list. Please try again.': '无法分享此清单，请重试。',
  'Failed to create local backup': '无法创建本机备份',
  'Failed to restore local backup': '无法恢复本机备份',
  'Cloud backup failed': '云端备份失败',
  'Cloud restore failed': '云端恢复失败',
  'No matching currency': '未找到匹配的货币',
  'Try its three-letter code or full name.': '请尝试输入三位货币代码或完整名称。',
  'Default Currency': '默认货币',
  'Choose Currency': '选择货币',
  'Search by code or currency name': '搜索货币代码或名称',
  'Recent': '最近使用',
  'default': '默认',
  'recent': '最近使用',
  '(default)': '（默认）',
  'Appearance': '外观',
  'My List': '我的清单',
  "Today's Shopping": '今日购物',
  'TO BUY': '待购买',
  'PURCHASED': '已购买',
  'SELECTED ITEMS': '所选商品',
  'ALL LISTS': '所有清单',
  'Note': '备注',
  'total': '总计',
  'totals': '总计',
  'No items yet.': '暂无商品。',
  'All': '全部',
  'This empty list will be deleted.': '此空清单将被删除。',
  'This record changed elsewhere. Both versions are kept; review them in Profile → Cloud Sync.':
      '此记录已在其他设备上更改，两个版本均已保留，请前往「个人中心 → 云同步」确认。',
  'This record changed elsewhere. Review changes in Profile → Cloud Sync.':
      '此记录已在其他设备上更改，请前往「个人中心 → 云同步」确认。',
  'Move undone.': '已撤销移动。',
  'Could not open this shopping list. Your data is still on this device.':
      '无法打开此购物清单，您的数据仍保存在本机。',
  'Could not undo the move. The items or lists may have changed; your latest data is kept.':
      '无法撤销移动，商品或清单可能已更改，最新数据已保留。',
  'Could not undo the deletion because this list changed. Your latest data is kept.':
      '此清单已更改，无法撤销删除，最新数据已保留。',
  'Could not save this change. Your selection is kept; please try again.':
      '无法保存更改，已保留您的选择，请重试。',
  'Create List': '创建清单',
  'Preferences': '偏好设置',
  'Account & Data': '账号与数据',
  'Language': '语言',
  'Language Preference': '语言设置',
  'English': '英语',
  'Bangla': '孟加拉语',
  'Number Format': '数字格式',
  'Automatic': '自动',
  'International': '国际格式',
  'South Asian': '南亚格式',
  'Match each currency’s region': '按各货币所属地区显示',
  'Follow your device region': '跟随设备地区设置',
  'System': '跟随系统',
  'Light': '浅色',
  'Dark': '深色',
  'Edit Profile': '编辑个人资料',
  'Change Photo': '更换头像',
  'Choose From Gallery': '从相册选择',
  'Remove Photo': '移除头像',
  'Google Account': 'Google 账号',
  'Email cannot be edited here.': '无法在此更改邮箱地址。',
  'Saved on this device. Your Google account name and photo stay unchanged.':
      '仅保存在本机，不会更改 Google 账号的名称和头像。',
  'Your saved profile could not be loaded. Please restart the app.':
      '无法加载已保存的个人资料，请重启应用。',
  'Sign In Required': '需要登录',
  'Sign in Required': '需要登录',
  'Sign In': '登录',
  'Sign In with Google': '使用 Google 登录',
  'Sign Out': '退出登录',
  'Sign Out?': '退出登录？',
  'Your lists stay accessible on this device. Cloud sync pauses until you sign back into the same account.\n\nCloud data and backups are kept. Other accounts have separate history.':
      '您的清单仍可在本机访问。云同步将暂停，直到您重新登录同一账号。\n\n云端数据和备份会保留，其他账号的历史记录互相独立。',
  'You need to sign in with your Google account to use cloud backup and synchronization features.':
      '请登录 Google 账号以使用云端备份和同步功能。',
  'You need to sign in with your Google account to use cloud backup features.':
      '请登录 Google 账号以使用云端备份功能。',
  'Cloud Sync': '云同步',
  'Retry Sync': '重试同步',
  'Review Changes': '查看更改',
  'The same record changed in two places. Review both versions before choosing. Other edits can continue syncing.':
      '同一记录在两处被更改，请查看两个版本后再选择，其他更改可继续同步。',
  'This is part of an item transfer. Your choice applies to both related dates below.':
      '此更改涉及商品移动，您的选择将应用于以下两个相关日期。',
  'This Device': '本机版本',
  'Saved Version': '已保存的版本',
  'Keep Saved Version': '保留已保存的版本',
  'Use My Changes': '使用我的更改',
  'Advanced Backup & Restore': '高级备份与恢复',
  'File and Google Drive backups': '文件与 Google 云端硬盘备份',
  'Backup & Restore': '备份与恢复',
  'Restore Backup?': '恢复备份？',
  'Restoring this backup will replace your current local ShopTrack data. If cloud sync is enabled, these changes also sync to this account’s other devices. Export a backup first if you want to keep the current version.':
      '恢复此备份将替换本机当前的 ShopTrack 数据。若已启用云同步，更改也会同步至此账号的其他设备。如需保留当前版本，请先导出备份。',
  'Restore': '恢复',
  'Data restored successfully': '数据已恢复',
  'Local backup created successfully': '本机备份已创建',
  'No backup found in your cloud storage.': '未在云端找到备份。',
  'Could not save your choice. Please try again.': '无法保存您的选择，请重试。',
  'Could not save the currency preference.': '无法保存货币设置。',
  'Could not save the language preference.': '无法保存语言设置。',
  'Default currency changed to {currency}. Existing items were not changed.':
      '默认货币已改为 {currency}，现有商品保持不变。',
  'Cloud Backup': '云端备份',
  'Back up to your Google account': '备份到 Google 账号',
  'Sign in to enable cloud backup': '登录以启用云端备份',
  'Lists stay on this device': '清单保留在本机',
  'Your Profile': '您的个人资料',
  'Welcome to ShopTrack': '欢迎使用 ShopTrack',
  'Sign in with Google to use cloud backup.': '登录 Google 账号以使用云端备份。',
  'Could not save this change. Please try again.': '无法保存更改，请重试。',
  'Could not move this item. Please try again.': '无法移动此商品，请重试。',
  'Item deleted': '商品已删除',
  'Item saved, but the recent currency shortcut could not be updated.':
      '商品已保存，但无法更新最近使用的货币。',
  'About ShopTrack': '关于 ShopTrack',
  'Your Shopping Companion': '您的购物好帮手',
  'Plan your shopping, track purchases and keep your history close—even offline.':
      '规划购物、记录购买情况，离线也能随时查看历史记录。',
  'App Version': '应用版本',
  '© 2026 ShopTrack Team': '© 2026 ShopTrack 团队',
  'Stay organized. Shop smarter.': '清单井然有序，购物更轻松。',
  'Find items across your shopping dates': '查找不同日期的购物商品',
  'Close': '关闭',
  'Back': '返回',
  'Back to History': '返回历史记录',
  'Day': '日',
  'Month': '月',
  'Year': '年',
  'Search currencies': '搜索货币',
  'Clear search': '清除搜索',
  'Search items': '搜索商品',
  'e.g. Eggs': '例如：鸡蛋',
  'e.g. Household': '例如：日用品',
  'e.g. Grandmother': '例如：奶奶',
  'List name': '清单名称',
  'New shopping list': '新建购物清单',
  'Rename shopping list': '重命名购物清单',
  'Move to List': '移至清单',
  'Choose where the selected items should go.': '选择所选商品的目标清单。',
  'No other lists yet': '暂无其他清单',
  'Create another list, then move these items into it.': '请先创建另一个清单，再将商品移入。',
  'Undo': '撤销',
  'Manage this shopping list.': '管理此购物清单。',
  'Cancel Selection': '取消选择',
  'Select All': '全选',
  'Deselect All': '取消全选',
  'Selected': '已选择',
  'Item': '件商品',
  'Items': '件商品',
  'item': '件商品',
  'items': '件商品',
  'list': '个清单',
  'lists': '个清单',
  'Copy or Share Selected Items': '复制或分享所选商品',
  'Date options': '日期选项',
  'Previous month': '上个月',
  'Next month': '下个月',
  'Add an earlier record or plan a future trip.': '补记过去的购物，或规划未来的采购。',
  'Choose Theme': '选择主题',
  'Light Theme': '浅色主题',
  'Dark Theme': '深色主题',
  'Golden Summer': '金色盛夏',
  'Blooming Spring': '繁花春日',
  'Tranquil Ocean': '宁静海洋',
  'Ember Autumn': '如火金秋',
  'Silent Midnight': '静谧午夜',
  'Ethereal Aurora': '梦幻极光',
  'Bleeding Moonlight': '绯红月夜',
  'Ancient Forest': '古老森林',
  'Profile Photo': '头像',
  'Choose how your profile appears in ShopTrack.': '设置您在 ShopTrack 中显示的个人资料。',
  'Display Name': '显示名称',
  'Only used in ShopTrack': '仅用于 ShopTrack',
  'Create Local Backup': '创建本机备份',
  'Export your data to a JSON file': '将数据导出为 JSON 文件',
  'Restore from Local File': '从本机文件恢复',
  'Select a previously saved JSON backup': '选择之前保存的 JSON 备份',
  'Back up to Cloud': '备份到云端',
  'Sync your data to Google Drive App Data': '将数据备份至 Google 云端硬盘的应用数据空间',
  'Restore from Cloud': '从云端恢复',
  'Download your latest cloud backup': '下载最新的云端备份',
  'Synced': '已同步',
  'Lists, items, prices, quantities and history.': '清单、商品、价格、数量和历史记录。',
  'On This Device': '在本机上',
  'Appearance and your ShopTrack profile.': '外观设置和 ShopTrack 个人资料。',
  'Use Another Device': '在其他设备上使用',
  'Sign in to the same account to load your lists.': '登录同一账号以获取您的清单。',
  'Kilogram (kg)': '千克（kg）',
  'Gram (g)': '克（g）',
  'Litre (L)': '升（L）',
  'Millilitre (mL)': '毫升（mL）',
  'Piece (pc)': '件（pc）',
  'Packet': '包',
  'Package': '包装',
  'Item name is required': '请输入商品名称',
  'Unit required for Price per Unit': '按单价计价时请选择单位',
  'Last used price': '上次使用的价格',
  'Double tap to change currency': '双击更改货币',
  'Price per': '单价 /',
  'Price per unit': '单价',
  'Total': '合计',
  'This quantity cannot be saved exactly.': '无法精确保存此数量。',
  'Enter an exact price with up to 2 decimals.': '请输入可精确保存的价格，最多保留两位小数。',
  'This total cannot be saved exactly.': '无法精确保存此总金额。',
};
